blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post/create/', views.post_create, name='post_create'),
    path('post/modify/<int:post_id>/', views.post_modify, name='post_modify'),
    path('post/delete/<int:post_id>/', views.post_delete, name='post_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('common/', include('common.urls')),
    path('habit/', include('habit_tracker.urls')),
    path('blog/', include('blog.urls')),
    # path('public_def/', include('public_def.urls')),
    path('chart/', include('chart.urls')),
]

habit_tracker/urls.py
from django.urls import path
from . import views

app_name = 'habit'

urlpatterns = [
    path('', views.index),
    path('detail', views.index, name='index'),
    path('add_pixel/', views.add_pixel, name='add_pixel'),
    path('delete_pixel/', views.delete_pixel, name='delete_pixel'),
    path('create_graph/', views.create_graph, name='create_graph'),
    path('delete_graph/', views.delete_graph, name='delete_graph'),
]

habit_tracker/models.py
from django.db import models

# Create your models here.

habit_tracker/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest
from django.utils import timezone
from dotenv import load_dotenv
import requests
import os
# Create your views here.

load_dotenv('../.env')

pixela_endpoint = 'https://pixe.la/v1/users'
PIXELA_TOKEN = os.getenv('PIXELA_TOKEN')
USER_NAME = 'redtraining'
# GRAPH_ID = 'test1'
# TODAY = timezone.localdate().strftime('%Y%m%d')

headers = {
    'X-USER-TOKEN': PIXELA_TOKEN}


@login_required(login_url='common:login')
def index(request: HttpRequest):
    try:
        res = requests.get(
            f'{pixela_endpoint}/{USER_NAME}/graphs', headers=headers)
        graph_list: list = res.json()['graphs']
    except:
        graph_list = []
        graph_id = ''
        make_messages(request, res)
    graph_id = request.GET.get('graph_id')
    context = {
        'graph_list': graph_list,
        'graph_id': graph_id if graph_id else graph_list[0]['id'] if graph_list else '',
        'today': timezone.localdate().strftime('%Y-%m-%d'),
    }
    return render(request, 'habit_tracker/index.html', context)


@login_required(login_url='common:login')
def create_graph(request: HttpRequest):
    if request.method == 'POST':
        req_body = {
            'id': request.POST.get('graph_id'),
            'name': request.POST.get('graph_name'),
            'unit': request.POST.get('unit'),
            'type': request.POST.get('type'),
            'color': request.POST.get('color'),
            'timezone': 'Asia/Seoul',
        }
        res = requests.post(
            f'{pixela_endpoint}/{USER_NAME}/graphs',
            headers=headers,
            json=req_body,
        )
        make_messages(request, res)
        return redirect(reverse('habit:index') + '?graph_id=' + req_body['id'])

    colors = {
        'green': 'shibafu',
        'red': 'momiji',
        'blue': 'sora',
        'yellow': 'ichou',
        'purple': 'ajisai',
        'black': 'kuro',
    }

    return render(request, 'habit_tracker/create_graph.html', {'colors': colors})


@login_required(login_url='common:login')
def add_pixel(request: HttpRequest):
    graph_id = request.POST.get('graph_id')
    date = ''.join(request.POST.get('date').split('-'))
    quantity = request.POST.get('quantity')

    post_value = {
        'date': date,
        'quantity': quantity,
    }
    res = requests.post(
        f'{pixela_endpoint}/{USER_NAME}/graphs/{graph_id}',
        headers=headers,
        json=post_value,
    )
    make_messages(request, res)

    return redirect(reverse('habit:index') + '?graph_id=' + graph_id)


@login_required(login_url='common:login')
def delete_pixel(request: HttpRequest):
    graph_id = request.POST.get('graph_id')
    date = ''.join(request.POST.get('date').split('-'))
    print(date)
    res = requests.delete(
        f'{pixela_endpoint}/{USER_NAME}/graphs/{graph_id}/{date}',
        headers=headers,
    )
    print('res : ' + res.text)
    make_messages(request, res)

    return redirect(reverse('habit:index') + '?graph_id=' + graph_id)


@login_required(login_url='common:login')
def delete_graph(request: HttpRequest):
    graph_id = request.POST.get('graph_id')
    token = request.POST.get('token')
    res = requests.delete(
        f'{pixela_endpoint}/{USER_NAME}/graphs/{graph_id}',
        headers={'X-USER-TOKEN': token},
    )
    make_messages(request, res)

    return redirect('habit:index')


def make_messages(request: HttpRequest, res: requests.Response):
    res_data = res.json()
    isSuccess = res_data['isSuccess']
    if isSuccess:
        messages.add_message(request, messages.SUCCESS, res_data['message'])
    else:
        messages.add_message(request, messages.ERROR, res_data['message'])

templates/habit_tracker/create_graph.html
{% extends 'base.html' %}
{% block content %}
  <div class="container my-3">
    <h1>습관 기록 추가</h1>
    <form action="{% url 'habit:create_graph' %}" method="post" id="createForm" onsubmit="event.preventDefault(); onCreateSubmit();">
      {% csrf_token %}
      <div class="form-group">
        <label for="graph_id">ID:</label>
        <input type="text" class="form-control" name="graph_id" id="graph_id">
      </div>
      <div class="form-group">
        <label for="graph_name">NAME:</label>
        <input type="text" class="form-control" name="graph_name" id="graph_name">
      </div>
      <div class="form-group">
        <label for="unit">UNIT:</label>
        <input type="text" class="form-control" name="unit" id="unit">
      </div>
      <label>TYPE:</label>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="type" id="int" value="int" checked="checked">
        <label class="form-check-label" for="int">int</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="type" id="float" value="float">
        <label class="form-check-label" for="float">float</label>
      </div>
      <div>
        <label>COLOR:</label>
        {% for key, value in colors.items %}
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="color" id="{{ key }}" value="{{ value }}">
            <label class="form-check-label" for="{{ key }}">{{ key }}</label>
          </div>
        {% endfor %}
      </div>
      <button class="btn btn-primary mt-3">추가</button>
    </form>
  </div>
{% endblock content %}
{% block script %}
  <script type="text/javascript">
    name = document
      .getElementById('graph_name')
      .value;
    createForm = document.getElementById('createForm');

    function onCreateSubmit() {
      if (confirm(name + ' 그래프를 생성할까요?')) {
        createForm.submit();
      }
    }
  </script>
{% endblock script %}

templates/habit_tracker/index.html
{% extends 'base.html' %}
{% block content %}
  <div class="container my-3">
    <h1 class="d-flex justify-content-center">습관 기록</h1>

    <!-- 그래프 리스트 -->
    {% if graph_list %}
      <div class="d-flex justify-content-center mb-3">
        {% for graph in graph_list %}
          <a class="badge rounded-pill bg-secondary mx-1" href="{% url 'habit:index' %}?graph_id={{ graph.id }}">{{ graph.name }}</a>
        {% endfor %}
      </div>
    {% endif %}

    <!-- 픽셀 그래프 -->
    <div class="d-flex justify-content-center mb-3">
      <iframe src="https://pixe.la/v1/users/redtraining/graphs/{{ graph_id }}.html?mode=simple" height="155" width="720" frameborder="0"></iframe>
    </div>

    <!-- 메시지 -->
    {% if messages %}
      <ul>
        {% for message in messages %}
          <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
            {{ message }}
          </li>
        {% endfor %}
      </ul>
    {% endif %}

    <!-- 픽셀 -->
    <form action="{% url 'habit:add_pixel' %}" method="post" class="my-2">
      {% csrf_token %}
      <input type="hidden" name="graph_id" value="{{ graph_id }}">
      <div class="form-group mb-1">
        <label for="date">언제?</label>
        <input type="date" class="form-control" name="date" id="date" value="{{ today }}">
      </div>
      <div class="form-group">
        <label for="quantity">얼마나?</label>
        <input type="number" class="form-control" name="quantity" id="quantity">
      </div>
      <!-- 픽셀 저장 -->
      <div class="float-end">
        <button type="submit" class="btn btn-primary mt-2">저장</button>
      </div>
    </form>

    <!-- 픽셀 삭제 -->
    <form action="{% url 'habit:delete_pixel' %}" method="post" id="delPixelForm" class="mb-3">
      {% csrf_token %}
      <input type="hidden" name="graph_id" value="{{ graph_id }}">
      <input type="hidden" name="date">
      <button type="button" class="delete btn btn-sm btn-outline-secondary">삭제</button>
    </form>

    <!-- 그래프 -->
    <div class="mb-3">
      <!-- 디테일 -->
      <div class="d-flex justify-content-center">
        <a class="btn btn-link" href="https://pixe.la/v1/users/redtraining/graphs/{{ graph_id }}.html">그래프 디테일</a>
      </div>
      <!-- 그래프 추가 -->
      <a href="{% url 'habit:create_graph' %}" class="btn btn-sm btn-primary mb-1">그래프 추가</a>
      <!-- 그래프 삭제 -->
      <form action="{% url 'habit:delete_graph' %}" method="post" id="delGraphForm">
        {% csrf_token %}
        <input type="hidden" name="graph_id" value="{{ graph_id }}">
        <input type="hidden" name="token">
        <button type="button" class="delete delete-graph btn btn-sm btn-outline-secondary">그래프 삭제</button>
      </form>
    </div>
  </div>

{% endblock content %}
{% block script %}
  <script type="text/javascript">
    delButtons = document.getElementsByClassName('delete');
    Array
      .from(delButtons)
      .forEach((btn) => {
        btn.addEventListener('click', () => {
          if (confirm('삭제하시겠습니까?')) {
            if (btn.className.includes('graph')) {
              token = prompt('토큰을 입력하세요: ');
              if (token == '' | token == null) 
                return;
              document
                .querySelector('input[name=token]')
                .value = token;
            } else {
              let date = document
                .getElementById('date')
                .value;
              document
                .querySelector('#delPixelForm > input[name=date]')
                .value = date;
            }

            btn
              .parentElement
              .submit();
          }
        });
      });
  </script>
{% endblock script %}