blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post/create/', views.post_create, name='post_create'),
    path('post/modify/<int:post_id>/', views.post_modify, name='post_modify'),
    path('post/delete/<int:post_id>/', views.post_delete, name='post_delete'),
]

chart/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'chart'

urlpatterns = [
    path('', views.index, name='index'),
    path('hayul_growth/', login_required(views.ChartView.as_view(),
         login_url='common:login'), name='growth_chart'),
    path('hayul_growth/get_data/', views.get_data, name='growth_data'),
    path('hayul_growth/list/', login_required(views.HayulGrowthListView.as_view(),
         login_url='common:login'), name='growth_list'),
    path('hayul_growth/add/', login_required(views.HayulGrowthCreateView.as_view(),
         login_url='common:login'), name='growth_add'),
    path('hayul_growth/<int:pk>/',
         login_required(views.HayulGrowthUpdateView.as_view(),
                        login_url='common:login'), name='growth_update'),
    path('hayul_growth/<int:pk>/delete',
         login_required(views.HayulGrowthDeleteView.as_view(),
                        login_url='common:login'), name='growth_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('common/', include('common.urls')),
    path('habit/', include('habit_tracker.urls')),
    path('blog/', include('blog.urls')),
    # path('public_def/', include('public_def.urls')),
    path('chart/', include('chart.urls')),
]

chart/models.py
from django.db import models

# Create your models here.


class HayulGrowth(models.Model):
    year_month = models.DateField(verbose_name='연월')
    height = models.FloatField(verbose_name='키')
    weight = models.FloatField(verbose_name='몸무게')

    class Meta:
        ordering = ['year_month']

chart/forms.py
from django import forms
from .models import HayulGrowth


class HayulGrowthForm(forms.ModelForm):

    class Meta:
        model = HayulGrowth
        fields = ("year_month", "height", "weight")
        labels = {
            "year_month": "연월",
            "height": "키",
            "weight": "몸무게",
        }

chart/views.py
from typing import Any
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# from .forms import HayulGrowthForm
from .models import HayulGrowth

# Create your views here.


def index(request: HttpRequest):
    return render(request, 'chart/index.html')


# @login_required(login_url='common:login')
# def show_chart(request: HttpRequest):
#     return render(request, 'chart/show_chart.html')


class ChartView(TemplateView):
    template_name = 'chart/show_chart.html'
    # 템플릿으로 차트 이름을 context로 넘겨주면 좋을 듯.


@login_required(login_url='common:login')
def get_data(request):
    objects = HayulGrowth.objects.all()
    data = {
        'result': [
            {'year_month': obj.year_month, 'height': obj.height, 'weight': obj.weight} for obj in objects
        ]
    }

    return JsonResponse(data)


class HayulGrowthListView(ListView):
    model = HayulGrowth


# FormView를 활용할 수도 있는데, 아래와 같이 CreateView가 더욱 간결함.
# 다만 템플릿 이름은 '모델명_form.html'
# class HayulGrowthFormView(FormView):
#     form_class = HayulGrowthForm
#     template_name = "chart/post_form.html"
#     success_url = reverse_lazy("chart:show_chart")

#     def get(self, request):
#         form = self.form_class
#         return render(request, self.template_name, {"form": form})

#     def form_valid(self, form) -> HttpResponse:
#         return super().form_valid(form)


class HayulGrowthCreateView(CreateView):
    model = HayulGrowth
    fields = ['year_month', 'height', 'weight']
    success_url = reverse_lazy("chart:growth_chart")


class HayulGrowthUpdateView(UpdateView):
    model = HayulGrowth
    fields = ['year_month', 'height', 'weight']
    success_url = reverse_lazy("chart:growth_chart")


class HayulGrowthDeleteView(DeleteView):
    model = HayulGrowth
    fields = ['year_month', 'height', 'weight']
    success_url = reverse_lazy("chart:growth_list")

templates/chart/hayulgrowth_form.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <h5 class="my-3 text-center">데이터 입력</h5>
    <form method="post">
      {% csrf_token %}
      {% include 'form_errors.html' %}
      <label for="title">연월</label>
      <input type="date" name="year_month" id="year_month" class="form-control" value="{{ form.year_month.value|date:'Y-m-d'|default_if_none:'' }}">
      <label for="height">키</label>
      <input type="number" step="0.1" name="height" id="height" class="form-control" value="{{ form.height.value|default_if_none:'' }}">
      <label for="weight">몸무게</label>
      <input type="number" step="0.1" name="weight" id="weight" class="form-control" value="{{ form.weight.value|default_if_none:'' }}">
      {% comment %} {{ form.as_p }} {% endcomment %}
      <div class="mt-3 text-end">
        <button class="btn btn-primary">저장하기</button>
      </div>
    </form>
  </div>
{% endblock content %}
{% block script %}
<script>
  if(year_month.value == ''){
    year_month.value = new Date().toISOString().split('T')[0];
  }
</script>
{% endblock script %}

templates/chart/hayulgrowth_list.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <h1 class="text-center my-3">키,몸무게 리스트</h1>
    <ul>
      {% for obj in object_list %}
        <li class="d-flex justify-content-center my-1">
          <span class="mx-3">
            {{ obj.year_month }}
            /
            {{ obj.height }}cm /
            {{ obj.weight }}kg
          </span>
          <a href="{% url 'chart:growth_update' obj.pk %}" class="btn btn-sm btn-secondary mx-1">수정</a>
          <form onSubmit="return confirm('삭제하시겠습니까?');" action="{% url 'chart:growth_delete' obj.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" value="삭제" class="btn btn-sm btn-danger mx-1">
          </form>
        </li>
      {% endfor %}
    </ul>
    <div class="text-center">
      <a href="{% url 'chart:growth_chart' %}" class="mx-3">그래프</a>
      <a href="{% url 'chart:growth_add' %}" class="btn btn-sm btn-primary">데이터 추가</a>
    </div>
  </div>
{% endblock content %}

templates/chart/index.html
{% extends 'base.html' %}
{% block content %}
  <h1>차트앱입니다.</h1>
  <a href="{% url 'chart:growth_chart' %}">하율이 성장 그래프</a>
{% endblock content %}

templates/chart/show_chart.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <h1 class="text-center">키, 몸무게 그래프</h1>
    <div class="my-3">
      <canvas id="myChart"></canvas>
    </div>
    <div class="text-center">
      <a href="{% url 'chart:growth_list' %}" class="mx-3">리스트</a>
      <a href="{% url 'chart:growth_add' %}" class="btn btn-sm btn-primary">데이터 추가</a>
    </div>
  </div>
{% endblock content %}
{% block script %}

  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

  <script>
    const ctx = document.getElementById('myChart');
    const showChart = async () => {
      let response = await fetch('/chart/hayul_growth/get_data/');
      let jsonData = await response.json();
      let growth_data = jsonData.result;

      const data = {
        labels: growth_data.map(data => data.year_month),
        datasets: [
          {
            label: '키',
            data: growth_data.map(data => data.height),
            borderWidth: 1
          }, {
            label: '몸무게',
            data: growth_data.map(data => data.weight),
            borderWidth: 1
          }
        ]
      };

      const options = {
        scales: {
          y: {
            beginAtZero: false
          }
        }
      };
      
      new Chart(ctx, {
        type: 'line',
        data: data,
        options: options,
      });
    }
    showChart();
  </script>
{% endblock script %}