blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post/create/', views.post_create, name='post_create'),
    path('post/modify/<int:post_id>/', views.post_modify, name='post_modify'),
    path('post/delete/<int:post_id>/', views.post_delete, name='post_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('common/', include('common.urls')),
    path('habit/', include('habit_tracker.urls')),
    path('blog/', include('blog.urls')),
    # path('public_def/', include('public_def.urls')),
    path('chart/', include('chart.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.


class BlogPost(models.Model):
    title = models.CharField(max_length=50)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField()
    mod_date = models.DateTimeField(default=timezone.now)
    tag = models.CharField(max_length=50)
    content = models.TextField()
    private = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.title

blog/forms.py
from django import forms
from .models import BlogPost


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'tag', 'content', 'private']
        labels = {
            'title': '제목',
            'tag': '태그',
            'content': '내용',
            'private': '공개 여부',
        }

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest, HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.core.paginator import Paginator
from .models import BlogPost
from .forms import BlogPostForm
# Create your views here.


def index(request: HttpRequest):
    all_posts = BlogPost.objects.order_by('-pub_date')

    selected_tag = request.GET.get('tag')
    if selected_tag:
        selected_posts = BlogPost.objects.filter(
            tag__contains=selected_tag).order_by('-pub_date')
    else:
        selected_tag = ''
        selected_posts = all_posts

    # 페이지네이션
    paginator = Paginator(selected_posts, 5)
    page_number = request.GET.get('page')
    if not page_number:
        page_number = 1
    page_obj = paginator.get_page(page_number)

    # 태그
    tag_list: list[str] = []
    for post in all_posts:
        tag_list += post.tag.replace(' ', '').split(',')
    tags = set(tag_list)
    tags = sorted(tags, key=lambda tag: tag.lower())

    context = {
        'page_obj': page_obj,
        'tags': tags,
        'selected_tag': selected_tag
    }

    return render(request, 'blog/index.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(BlogPost, pk=post_id)
    if post.private and post.author.username != request.user.username:
        return HttpResponse('<h1>비공개글입니다.</h1>')
    else:
        context = {'post': post}
        return render(request, 'blog/post_detail.html', context)


@login_required(login_url='common:login')
def post_create(request: HttpRequest):
    if request.method == 'POST':
        form = BlogPostForm(request.POST)
        if form.is_valid():
            post: BlogPost = form.save(commit=False)
            post.author = request.user
            post.pub_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', post.pk)
    else:
        form = BlogPostForm()
    return render(request, 'blog/post_form.html', {'form': form})


@login_required(login_url='common:login')
def post_modify(request: HttpRequest, post_id):
    post: BlogPost = get_object_or_404(BlogPost, pk=post_id)

    if request.user != post.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('blog:post_detail', post_id)

    if request.method == 'POST':
        # instance 기준으로 form 생성하되 data 값으로 덮어쓰기
        form = BlogPostForm(data=request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.mod_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', post_id)
    else:
        form = BlogPostForm(instance=post)

    context = {
        'form': form
    }
    return render(request, 'blog/post_form.html', context)


@login_required(login_url='common:login')
def post_delete(request: HttpRequest, post_id):
    post = get_object_or_404(BlogPost, pk=post_id)
    if request.user != post.author:
        messages.error(request, '권한이 없습니다.')
        return redirect('blog:post_detail', post_id)

    post.delete()
    return redirect('blog:index')

templates/blog/index.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="my-3 text-center">
      <h1>블로그</h1>
    </div>
    <!-- 테이블 -->
    <table class="table text-center table-hover">
      <thead>
        <tr>
          <th scope="col">번호</th>
          <th scope="col">제목</th>
          <th scope="col">글쓴이</th>
          <th scope="col">글쓴날</th>
        </tr>
      </thead>
      <tbody>
        {% for post in page_obj %}
          <tr>
            <th scope="row">{{ post.pk }}</th>
            <td>
              <!-- onclick의 값이 true이면 href로 이동, false이면 이동 X -->
              <a href="{% url 'blog:post_detail' post.pk %}" onclick="return openOrPrivate('{{ post.author }}', '{{ post.private }}');">{{ post.title }}</a>
            </td>
            <td>{{ post.author }}</td>
            <td>{{ post.pub_date|date:"DATE_FORMAT" }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <!-- pagination -->
    <nav aria-label="page navigation">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?tag={{ selected_tag }}&page=1">처음</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?tag={{ selected_tag }}&page={{ page_obj.previous_page_number }}">이전</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <span class="page-link">처음</span></li>
          <li class="page-item disabled">
            <span class="page-link">이전</span></li>
        {% endif %}
        {% for page in page_obj.paginator.page_range %}
          <!-- 6페이지 앞으로 이동 버튼 -->
          {% if page == page_obj.number|add:-6 %}
            <li class="page-item">
              <a class="page-link" href="?tag={{ selected_tag }}&page={{ page_obj.number|add:-6 }}">...</a>
            </li>
          {% endif %}
          <!-- 전후 5페이지 표시 -->
          {% if page_obj.number|add:-5 <= page and page <= page_obj.number|add:5 %}
            {% if page_obj.number == page %}
              <li class="page-item active">
            {% else %}
              <li class="page-item">
            {% endif %}
                <a class="page-link" href="?tag={{ selected_tag }}&page={{ page }}">{{ page }}</a>
              </li>
          {% endif %}
          <!-- 6페이지 뒤로 이동 버튼 -->
          {% if page == page_obj.number|add:6 %}
            <li class="page-item">
              <a class="page-link" href="?tag={{ selected_tag }}&page={{ page_obj.number|add:6 }}">...</a>
            </li>
          {% endif %}
        {% endfor %}
          <!-- <li class="page-item"> <span class="page-link"> {{ page_obj.number }} / {{ page_obj.paginator.num_pages }} page </span> </li> -->
          {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?tag={{ selected_tag }}&page={{ page_obj.next_page_number }}">다음</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?tag={{ selected_tag }}&page={{ page_obj.paginator.num_pages }}">마지막</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <span class="page-link">다음</span></li>
            <li class="page-item disabled">
              <span class="page-link">마지막</span></li>
          {% endif %}
        </ul>
      </nav>
      <!-- pagination END -->

      <!-- Tag -->
      <div>
        <a class="badge rounded-pill bg-secondary mx-1" href="{% url 'blog:index' %}">ALL</a>
        {% for tag in tags %}
          <a class="badge rounded-pill bg-secondary mx-1" href="{% url 'blog:index' %}?tag={{ tag }}">{{ tag }}</a>
        {% endfor %}
      </div>

      <!-- 글쓰기 버튼 -->
      <div class="d-flex justify-content-end">
        <a href="{% url 'blog:post_create' %}" class="btn btn-primary">글쓰기</a>
      </div>
    </div>
  {% endblock content %}
{% block script %}
<script>
  function openOrPrivate(author, isPrivate) {
    if (isPrivate == 'True' && author != '{{ request.user.username }}'){
      alert('비공개 글입니다.')
      return false;
    } else {
      return true;
    }
  }
</script>
{% endblock script %}

templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load blog_filter %}
{% block head %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link type="text/css" rel="stylesheet" href="{% static 'code-hilite.css' %}">
{% endblock head %}
{% block content %}
  <div class="container mb-5">

    <!-- 메시지 -->
    {% if messages %}
      <div class="alert alert-danger my-3">
        {% for message in messages %}
          <strong>{{ message.tag }}</strong>
          <ul>
            <li>{{ message.message }}</li>
          </ul>
        {% endfor %}
      </div>
    {% endif %}

    <!-- 제목 -->
    <div class="my-3 text-center">
      <h1 style="display: inline-block">{{ post.title }}</h1>
      {% if post.private %}
        <span class="badge bg-warning text-dark">비공개</span>
      {% endif %}
    </div>
    
    <!-- 정보 -->
    <div class="d-flex flex-column align-items-end">
      <p>글쓴이:
        {{ post.author }}</p>
      <p class="text-end">쓴날:
        {{ post.pub_date }}
        <br>
        고친날:
        {{ post.mod_date }}</p>
      <p>태그:
        {{ post.tag }}</p>
    </div>

    <!-- 본문 -->
    <p>{{ post.content|mark }}</p>

    <!-- Floating button -->
    <div class="dropup">
      <button type="button" class="btn btn-primary shadow dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="bi bi-collection"></i>
      </button>
      <ul class="dropdown-menu">
        <!-- Dropdown menu links -->
        {% if post.author == request.user %}
          <li>
            <a href="javascript:void(0)" data-uri="{% url 'blog:post_delete' post.pk %}" id="delBtn" class="dropdown-item">
              <i class="bi bi-trash3"></i>
            </a>
          </li>
        {% endif %}
        <li>
          <a href="{% url 'blog:post_modify' post.pk %}" class="dropdown-item">
            <i class="bi bi-pen"></i>
          </a>
        </li>
        <li>
          <a href="{% url 'blog:index' %}" class="dropdown-item" href="#">
            <i class="bi bi-list-ol"></i>
          </a>
        </li>
      </ul>
    </div>
  </div>
{% endblock content %}

{% block script %}
  <script type="text/javascript">
    delBtn.addEventListener('click', (e) => {
      if (confirm('정말로 삭제하시겠습니까?')) {
        location.href = e.currentTarget.dataset.uri;
      }
    });

    tables = document.querySelectorAll('table');
    for(table of tables){
      table.classList.add('table');
    }
  </script>
{% endblock script %}

templates/blog/post_form.html
{% extends 'base.html' %}
{% block head %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock head %}
{% block content %}
  <div class="container">
    <h5 class="my-3 text-center">글쓰기</h5>
    <form method="post">
      {% csrf_token %}
      {% include 'form_errors.html' %}
      <label for="title">제목</label>
      <input type="text" name="title" id="title" class="form-control" value="{{ form.title.value|default_if_none:'' }}">
      <label for="tag">태그</label>
      <input type="text" name="tag" id="tag" class="form-control" value="{{ form.tag.value|default_if_none:'' }}">
      <label for="content">내용</label>
      <textarea name="content" id="content" class="form-control" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
      <input type="checkbox" id="private" name="private" value='true'>
      <label for="private">비공개</label>
      <div class="mt-3 text-end">
        <button class="btn btn-primary">저장하기</button>
      </div>
    </form>
  </div>
{% endblock content %}

{% block script %}
  <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
  <script>
    var simplemde = new SimpleMDE({
      element: document.getElementById("content"), 
      spellChecker: false,
      toolbar: [
        'bold', 'italic', 'strikethrough', '|', 
        'heading-smaller', 'heading-bigger', '|', 
        'code', 'quote', '|', 
        'unordered-list', 'ordered-list', '|',
        'link', 'image', 'table',
        {
          name: 'footnotes',
          action: addFootnotes,
          className: 'fa fa-superscript',
          title: 'Footnotes',
        }, '|',
        'horizontal-rule', '|',
        'preview'
        ],
      insertTexts: {
        link: ["[", "](){: target='_blank'}"],
      },
    });

    function addFootnotes(editor){
      var cm = editor.codemirror;
      var doc = cm.getDoc();
      var cursor = doc.getCursor();
      var pos = {
        line: cursor.line,
        ch: cursor.ch,
      }
      doc.replaceRange('[^] [^]:', pos);
      pos.ch += 2;
      doc.setCursor(pos);
      cm.focus();
    }
    

    if('{{ form.private.value }}' == 'True'){
      private.checked = true;
    }
  </script>
{% endblock script %}