blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post/create/', views.post_create, name='post_create'),
    path('post/modify/<int:post_id>/', views.post_modify, name='post_modify'),
    path('post/delete/<int:post_id>/', views.post_delete, name='post_delete'),
]

chart/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'chart'

urlpatterns = [
    path('', views.index, name='index'),
    path('hayul_growth/', login_required(views.ChartView.as_view(),
         login_url='common:login'), name='growth_chart'),
    path('hayul_growth/get_data/', views.get_data, name='growth_data'),
    path('hayul_growth/list/', login_required(views.HayulGrowthListView.as_view(),
         login_url='common:login'), name='growth_list'),
    path('hayul_growth/add/', login_required(views.HayulGrowthCreateView.as_view(),
         login_url='common:login'), name='growth_add'),
    path('hayul_growth/<int:pk>/',
         login_required(views.HayulGrowthUpdateView.as_view(),
                        login_url='common:login'), name='growth_update'),
    path('hayul_growth/<int:pk>/delete',
         login_required(views.HayulGrowthDeleteView.as_view(),
                        login_url='common:login'), name='growth_delete'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('common/', include('common.urls')),
    path('habit/', include('habit_tracker.urls')),
    path('blog/', include('blog.urls')),
    # path('public_def/', include('public_def.urls')),
    path('chart/', include('chart.urls')),
]

habit_record/urls.py
from django.urls import path
from . import views

app_name = 'habit'

urlpatterns = [
    path('', views.index, name='index'),
    path('add_pixel/', views.add_pixel, name='add_pixel'),
    path('delete_pixel/', views.delete_pixel, name='delete_pixel'),
    path('create_graph/', views.create_graph, name='create_graph'),
    path('delete_graph/', views.delete_graph, name='delete_graph'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="text/css" rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'style.css' %}">
    {% block head %}{% endblock head %}
    <title>RedTraining</title>
  </head>

  <body>
    {% include 'navbar.html' %}
    {% block content %}{% endblock content %}
    <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
    {% block script %}{% endblock script %}
  </body>

</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
  <div class="alert alert-danger">
    {% for field in form %}
      <!-- 필드 오류 -->
      {% if field.errors %}
        <div>
          <strong>{{ field.label }}</strong>
          {{ field.errors }}
        </div>
      {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
      <div>
        <strong>{{ error }}</strong>
      </div>
    {% endfor %}
  </div>
{% endif %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
  <div class="container my-3">
    <h1>홈페이지</h1>
  </div>
{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-light bg-light border-bottom">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">RedTraining</a>
    <!-- 햄버거 버튼 -->
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- offcanvas -->
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <!-- 헤더 -->
      <div class="offcanvas-header">
        {% if user.is_authenticated %}
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">{{ user.username }}</h5>
          <a class="nav-link" href="{% url 'common:logout' %}">로그아웃</a>
        {% else %}
          <a class="offcanvas-title nav-link" href="{% url 'common:login' %}">로그인</a>
          {% comment %} <a class="offcanvas-title nav-link" href="{% url 'common:signup' %}">회원가입</a> {% endcomment %}
        {% endif %}
        <a class="offcanvas-title nav-link" href="admin/">관리자</a>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <!-- 바디 -->
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'habit:index' %}">습관 기록</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:index' %}">블로그</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'chart:index' %}">차트</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>